# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(678, 314)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 651, 181))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.line_details_download = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_details_download.setObjectName("line_details_download")
        self.gridLayout.addWidget(self.line_details_download, 1, 1, 1, 1)
        self.line_drons_download = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_drons_download.setObjectName("line_drons_download")
        self.gridLayout.addWidget(self.line_drons_download, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.line_card_download = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_card_download.setObjectName("line_card_download")
        self.gridLayout.addWidget(self.line_card_download, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.load_button_drones = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.load_button_drones.setObjectName("load_button_drones")
        self.gridLayout.addWidget(self.load_button_drones, 0, 2, 1, 1)
        self.load_button_details = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.load_button_details.setObjectName("load_button_details")
        self.gridLayout.addWidget(self.load_button_details, 1, 2, 1, 1)
        self.load_button_tech_cards = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.load_button_tech_cards.setObjectName("load_button_tech_cards")
        self.gridLayout.addWidget(self.load_button_tech_cards, 2, 2, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 200, 195, 51))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.download_all = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.download_all.setFont(font)
        self.download_all.setObjectName("download_all")
        self.gridLayout_2.addWidget(self.download_all, 0, 0, 1, 1)
        self.close = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.close.setFont(font)
        self.close.setObjectName("close")
        self.gridLayout_2.addWidget(self.close, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 678, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Комплектующие"))
        self.label_3.setText(_translate("MainWindow", "Тех. карты"))
        self.label.setText(_translate("MainWindow", "Дроны"))
        self.load_button_drones.setText(_translate("MainWindow", "..."))
        self.load_button_details.setText(_translate("MainWindow", "..."))
        self.load_button_tech_cards.setText(_translate("MainWindow", "..."))
        self.download_all.setText(_translate("MainWindow", "Загрузить"))
        self.close.setText(_translate("MainWindow", "Закрыть"))
